server:
  port: 8191

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Rasanjalee/V7-git-store-config
          search-paths:
            - 'service-config/*service'